### ISSUE TITLE
Keeps crashing 

### ISSUE THREAD

**Issue by TypicalGamer07** [xManager-App/xManager#266]
This app keeps crashing while selecting version drop down menu.

**Device**: Samsung Galaxy A13
**Software**: Android 13 (OneUI 5.0)
**Chipset**: Exynos 850
**RAM**: 6GB LPDDR4X

`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at n.sm.getCount(MainActivity.java:17641)
	at android.widget.ListView.setAdapter(ListView.java:612)
	at n.ef.onClick(MainActivity.java:5306)
	at android.view.View.performClick(View.java:7881)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
`

**Comment by Pabicchio** [comment]
Same, after opening the app i get the no api response as in the screenshot
![Screenshot_20230223-142548_xManager](https://user-images.githubusercontent.com/114694766/220920360-eade41c3-a2e8-4db3-a8f1-e02030456947.png)

and if I reload a few times i gets this:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at n.si.getCount(MainActivity.java:17377)
	at android.widget.ListView.setAdapter(ListView.java:581)
	at n.y.run(MainActivity.java:15488)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by zigzag2425** [comment]
Hello, I am having the dame problem on m'y nothing phone (1) running Android. 

Here is the error trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at n.si.getCount(MainActivity.java:17377)
	at android.widget.ListView.setAdapter(ListView.java:581)
	at n.mj.onCheckedChanged(MainActivity.java:1110)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:222)
	at android.widget.Switch.setChecked(Switch.java:1250)
	at n.p.run(MainActivity.java:15343)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:216)
	at android.os.Looper.loop(Looper.java:303)
	at android.app.ActivityThread.main(ActivityThread.java:7951)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by Mike92988** [comment]
Also happening to me with same error messages as above, s21 ultra

**Comment by madhurvarshney** [comment]
Same problem.
Device: Realme GT 2 Pro
Software: Android 13 (Realme UI 4)

**Comment by energ0n** [comment]
xManager is down until further notice. See the discord or telegram groups for APKs until then.

**Comment by zainkadir** [comment]
> Same, i have a Redmi note 10 pro with evolutionx android 13, after opening the app i get the no api response as in the screenshot
> ![Screenshot_20230223-142548_xManager](https://user-images.githubusercontent.com/114694766/220920360-eade41c3-a2e8-4db3-a8f1-e02030456947.png)
> 
> and if I reload a few times i gets this:
> java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
> 	at n.si.getCount(MainActivity.java:17377)
> 	at android.widget.ListView.setAdapter(ListView.java:581)
> 	at n.y.run(MainActivity.java:15488)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7868)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> 

Same phone, mine:

![Screenshot_2023-02-23-16-20-19-825_com.xc3fff0e.xmanager.jpg](https://user-images.githubusercontent.com/34738649/220967582-aefbe130-bed0-41bf-86e9-0ac520bd35dc.jpg)

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at n.sj.getCount(MainActivity.java:17509)
	at android.widget.ListView.setAdapter(ListView.java:581)
	at n.ee.onClick(MainActivity.java:5252)
	at android.view.View.performClick(View.java:7750)
	at android.view.View.performClickInternal(View.java:7727)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29115)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

**Comment by TypicalGamer07** [comment]
> xManager is down until further notice. See the discord or telegram groups for APKs until then. 

Provide the discord link please

**Comment by Notis21** [comment]
Same to me ,keeps crashing samsung s21 plus

**Comment by energ0n** [comment]
xManager v4.5 has been added to the releases section. 
Uninstall any previous xManager version and install v4.5 from the [releases section](https://github.com/xManager-App/xManager/releases) to resolve the specific issue in this thread.
