### ISSUE TITLE
App crashing while opening mirror link

### ISSUE THREAD

**Issue by kanishk-upadhyay** [xManager-App/xManager#299]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  realme x7 max
- Android Version:  13
- ROM Version:  realme UI 4.0
- xManager Version:  Version 4.8
```

### 📝 Description

steps to reproduce:
1. open xmanager
2. open latest release 
3. download 
4. mirror link

error:
Invalid intent operation: No Activity found to handle Intent { act=android.intent.action.VIEW dat= (has extras) }

Detailed error message:
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2187)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1831)
	at android.app.Activity.startActivityForResult(Activity.java:5555)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
	at android.app.Activity.startActivityForResult(Activity.java:5508)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at android.app.Activity.startActivity(Activity.java:6011)
	at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:830)
	at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:279)
	at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:376)
	at com.xc3fff0e.xmanager.MainActivity.e(MainActivity.java:10533)
	at n.ip.run(MainActivity.java:4481)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8380)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 📸 Screenshots

![Screenshot_2023-04-02-17-57-44-76_a5c01c4563cf301fdcc1087d689ebdc7](https://user-images.githubusercontent.com/66172350/229352784-a2ddd690-d4b7-4229-b35e-07d50f7927ca.jpg)

**Comment by xC3FFF0E** [comment]
This should be resolved by now. Let me know if the issue persists. Thanks!
